name: Flash published release
run-name: Flash release ${{ github.ref_name }}
on:
  release:
    types: [published]
jobs:
  download:
    runs-on: [ self-hosted, release ]
    steps:
      - name: Download target binary
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'ElectronVector/f303-staged-delivery'
          version: 'tags/${{ github.ref_name }}'
          file: 'f303'
          token: ${{ secrets.GITHUB_TOKEN }}
  flash:
    needs: download
    uses: ./.github/workflows/flash.yml
    with:
      target: release