name: Flash published release
run-name: Flash ${{ github.ref_name }}
on:
  release:
    types: [published]
jobs:
  deploy-release:
    runs-on: [ self-hosted, release ]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Download target binary
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'ElectronVector/f303-staged-delivery'
          version: 'tags/${{ github.ref_name }}'
          file: 'f303'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Flash target
        run: gdb-multiarch -x gdb-st-link-flash-and-exit.py f303